In [25]:
import torch.nn as nn
import torch
from torch import Tensor
model = nn.Sequential(
        nn.Linear(1, 2),
        nn.ReLU(),
        nn.Linear(2, 1)
    )

In [21]:
for i in model.parameters():
#     for j in i:
        print(i)


Parameter containing:
tensor([[-34.4000],
        [ -2.5200]], requires_grad=True)
Parameter containing:
tensor([2.1400, 1.2900], requires_grad=True)
Parameter containing:
tensor([[-1.3000,  2.2800]], requires_grad=True)
Parameter containing:
tensor([-0.5800], requires_grad=True)


In [26]:
with torch.no_grad():
    def setparam(p, v):
        p.mul_(0)
        p.add_(v)

    params = list(model.parameters())
    setparam(params[0][0][0], -34.4)
    setparam(params[0][1][0], -2.52)
    setparam(params[1][0], 2.14)
    setparam(params[1][1], 1.29)
    setparam(params[2][0][0], -1.30)
    setparam(params[2][0][1], 2.28)
    setparam(params[3][0], -0.58)
    print(params)

[Parameter containing:
tensor([[-34.4000],
        [ -2.5200]], requires_grad=True), Parameter containing:
tensor([2.1400, 1.2900], requires_grad=True), Parameter containing:
tensor([[-1.3000,  2.2800]], requires_grad=True), Parameter containing:
tensor([-0.5800], requires_grad=True)]


In [34]:
model.eval()
for i in range(10):
    print(model(Tensor([i/10])))

tensor([-0.4208], grad_fn=<AddBackward0>)
tensor([1.7866], grad_fn=<AddBackward0>)
tensor([1.2121], grad_fn=<AddBackward0>)
tensor([0.6375], grad_fn=<AddBackward0>)
tensor([0.0630], grad_fn=<AddBackward0>)
tensor([-0.5116], grad_fn=<AddBackward0>)
tensor([-0.5800], grad_fn=<AddBackward0>)
tensor([-0.5800], grad_fn=<AddBackward0>)
tensor([-0.5800], grad_fn=<AddBackward0>)
tensor([-0.5800], grad_fn=<AddBackward0>)
